#!/usr/bin/env sh
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# Layout config
yabai -m config window_gap                   6
yabai -m config window_placement             second_child
yabai -m config layout                       bsp
yabai -m config_auto_balance                 on
# yabai -m config bottom_padding               100

# set float layout for MBP display
space_indices_on_mbp_display="$(
    yabai -m query --displays \
        | jq -e 'map(select(.uuid == "2F917C32-1D54-4830-4A41-1078CDA43226")) | .[0].spaces[]'
)"
for index in "$space_indices_on_mbp_display"
do
    yabai -m config --space "$index" layout stack
done

# Mouse
yabai -m config mouse_modifier               ctrl
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off

# Debug
yabai -m config debug_output on

# Rules
# yabai -m rule --add app="^Calendar$"           manage=off
yabai -m rule --add app="^Disk Utility$"       manage=off
yabai -m rule --add app="^System Preferences$" manage=off

echo "yabai configuration loaded..."

